/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        bookMenu = new javax.swing.JMenu();
        addBookMenuItem = new javax.swing.JMenuItem();
        updateDeleteBooks = new javax.swing.JMenuItem();
        booksListMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addMemberMenuItem = new javax.swing.JMenuItem();
        updateDeleteMembersMenuItem = new javax.swing.JMenuItem();
        membersAllMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home - LMS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Welcome to the Library Management System");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lib.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 40, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        bookMenu.setText("Books");
        bookMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookMenuActionPerformed(evt);
            }
        });

        addBookMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        addBookMenuItem.setText("Add Books");
        addBookMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookMenuItemActionPerformed(evt);
            }
        });
        bookMenu.add(addBookMenuItem);

        updateDeleteBooks.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        updateDeleteBooks.setText("Update Or Delete Book");
        updateDeleteBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDeleteBooksActionPerformed(evt);
            }
        });
        bookMenu.add(updateDeleteBooks);

        booksListMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        booksListMenuItem.setText("All Books");
        booksListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksListMenuItemActionPerformed(evt);
            }
        });
        bookMenu.add(booksListMenuItem);

        jMenuBar1.add(bookMenu);

        jMenu2.setText("Members");

        addMemberMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        addMemberMenuItem.setText("Add Member");
        addMemberMenuItem.setToolTipText("");
        addMemberMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(addMemberMenuItem);

        updateDeleteMembersMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        updateDeleteMembersMenuItem.setText("Update Or Delete Members");
        updateDeleteMembersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDeleteMembersMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(updateDeleteMembersMenuItem);

        membersAllMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        membersAllMenuItem.setText("Members List");
        membersAllMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membersAllMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(membersAllMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bookMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bookMenuActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel2MouseClicked

    private void addBookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookMenuItemActionPerformed
        // TODO add your handling code here:
        new View.AddBook().setVisible(true);
        
    }//GEN-LAST:event_addBookMenuItemActionPerformed

    private void addMemberMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberMenuItemActionPerformed
        // TODO add your handling code here:
        new View.AddMember().setVisible(true);
    }//GEN-LAST:event_addMemberMenuItemActionPerformed

    private void membersAllMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membersAllMenuItemActionPerformed
        // TODO add your handling code here:
        new View.MembersList().setVisible(true);
    }//GEN-LAST:event_membersAllMenuItemActionPerformed

    private void booksListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksListMenuItemActionPerformed
        // TODO add your handling code here:
        new View.BooksList().setVisible(true);
    }//GEN-LAST:event_booksListMenuItemActionPerformed

    private void updateDeleteMembersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDeleteMembersMenuItemActionPerformed
        // TODO add your handling code here:
        new View.UpdateDeleteMembers().setVisible(true);
    }//GEN-LAST:event_updateDeleteMembersMenuItemActionPerformed

    private void updateDeleteBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDeleteBooksActionPerformed
        // TODO add your handling code here:
        new View.UpdateDeleteBook().setVisible(true);
    }//GEN-LAST:event_updateDeleteBooksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addBookMenuItem;
    private javax.swing.JMenuItem addMemberMenuItem;
    private javax.swing.JMenu bookMenu;
    private javax.swing.JMenuItem booksListMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem membersAllMenuItem;
    private javax.swing.JMenuItem updateDeleteBooks;
    private javax.swing.JMenuItem updateDeleteMembersMenuItem;
    // End of variables declaration//GEN-END:variables
}
